apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
  #namespace: advisordemo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        env:
          - name: "aws_secret"
            value: "AKIAI222221111BBBAAA"
        imagePullPolicy: Always
        name: nginx
        resources: {}
